site_name: Pipeline de Dados - Documentação
site_url: https://Luan-zanardo.github.io/data-pipeline/
repo_url: https://github.com/Luan-zanardo/data-pipeline
repo_name: Luan-zanardo/data-pipeline
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Toggle de tema claro/escuro.
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  icon:
    repo: fontawesome/brands/github-alt

nav:
  - Início: index.md
  - Projeto:
      - Etapas do Projeto: etapas.md
      - Arquitetura: arquitetura.md
      - Fluxo do Pipeline: pipeline.md
      - Modelo de Dados: modelo-dados.md
  - Execução:
      - Setup e Execução: setup.md
      - Como Executar: como-executar.md
  - Pipeline:
      - Geração de Massa: geracao-massa.md
      - Orquestração e Landing: orquestracao.md
      - Bronze e Silver: bronze-silver.md
      - Gold: gold.md
  - Visualização:
      - Metabase: metabase.md

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
